"""empty message

Revision ID: 2f9faf4951ef
Revises: 
Create Date: 2022-03-29 22:03:56.275754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9faf4951ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('animal_count', sa.Integer(), nullable=False),
    sa.Column('new_client', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('pets',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('prev_diagnosis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('veterinarians',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=15), nullable=False),
    sa.Column('speciality', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['veterinarians.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['pets.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('client_pet',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['clients.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['pets.patient_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'patient_id')
    )
    op.create_table('contact_information',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['clients.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_information')
    op.drop_table('client_pet')
    op.drop_table('appointment')
    op.drop_table('veterinarians')
    op.drop_table('pets')
    op.drop_table('clients')
    # ### end Alembic commands ###
